/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import BLL.BLLPedido;
import BLL.BLLCliente;
import BLL.BLLEndereco;
import BO.BEConstantes;
import java.awt.Color;

/**
 *
 * @author allan
 */
public class Modal extends javax.swing.JDialog {
    private BEConstantes objConstante = new BEConstantes();
    private BLLCliente bllCliente = new BLLCliente();
    private BLLPedido bllPedido = new BLLPedido();
    private BLLEndereco bllEndereco = new BLLEndereco();
    private FormPrincipal formPrincipal = new FormPrincipal();
    
    public Modal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setModal(true);
        
        lblDesc.setText(formPrincipal.objModal.getDesc());
        
        if(formPrincipal.objModal.getDeleteID() == 0) {
            lblConfirmDelete.setVisible(false);
            lblCancelDelete.setText("OK");
            lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross_150x150.png")));
            lblDesc.setForeground(new java.awt.Color(51,51,51));
        }
        else {
            lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question_150x150.png")));
            lblCancelDelete.setText("Cancelar");
            lblConfirmDelete.setVisible(true);
            lblDesc.setForeground(new java.awt.Color(51,51,51));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        lblIcone = new javax.swing.JLabel();
        pDesc = new javax.swing.JPanel();
        lblDesc = new javax.swing.JLabel();
        lblConfirmDelete = new javax.swing.JLabel();
        lblCancelDelete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcone.setBackground(new java.awt.Color(204, 204, 204));
        lblIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question_150x150.png"))); // NOI18N
        lblIcone.setOpaque(true);
        pPrincipal.add(lblIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 190));

        pDesc.setBackground(new java.awt.Color(255, 255, 255));

        lblDesc.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(51, 51, 51));

        lblConfirmDelete.setBackground(new java.awt.Color(0, 0, 47));
        lblConfirmDelete.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        lblConfirmDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmDelete.setText("Confirmar");
        lblConfirmDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfirmDelete.setOpaque(true);
        lblConfirmDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmDeleteMouseClicked(evt);
            }
        });

        lblCancelDelete.setBackground(new java.awt.Color(0, 0, 47));
        lblCancelDelete.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        lblCancelDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelDelete.setText("Cancelar");
        lblCancelDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelDelete.setOpaque(true);
        lblCancelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDescLayout = new javax.swing.GroupLayout(pDesc);
        pDesc.setLayout(pDescLayout);
        pDescLayout.setHorizontalGroup(
            pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDescLayout.createSequentialGroup()
                        .addGap(0, 117, Short.MAX_VALUE)
                        .addComponent(lblConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pDescLayout.setVerticalGroup(
            pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(pDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pPrincipal.add(pDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 270, 190));

        getContentPane().add(pPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelDeleteMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lblCancelDeleteMouseClicked

    private void lblConfirmDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmDeleteMouseClicked
        if(formPrincipal.objModal.getDesc() == objConstante.confirmDeleteCliente){
            if (bllCliente.deleteClientes(formPrincipal.objModal.getDeleteID())){
                lblDesc.setText(objConstante.successDelete);
                lblDesc.setForeground(Color.green);
                lblCancelDelete.setText("OK");
                lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_150x150.png")));
                lblConfirmDelete.setVisible(false);
            }
        }
        if(formPrincipal.objModal.getDesc() == objConstante.confirmDeletePedido){
            if (bllPedido.deletePedidos(formPrincipal.objModal.getDeleteID())){
                lblDesc.setText(objConstante.successDelete);
                lblDesc.setForeground(Color.green);
                lblCancelDelete.setText("OK");
                lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_150x150.png")));
                lblConfirmDelete.setVisible(false);
            }
        }
        if(formPrincipal.objModal.getDesc() == objConstante.confirmDeleteEndereco){
            if (bllEndereco.deleteEnderecos(formPrincipal.objModal.getDeleteID())){
                lblDesc.setText(objConstante.successDelete);
                lblDesc.setForeground(Color.green);
                lblCancelDelete.setText("OK");
                lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_150x150.png")));
                lblConfirmDelete.setVisible(false);
            }
        }
    }//GEN-LAST:event_lblConfirmDeleteMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCancelDelete;
    private javax.swing.JLabel lblConfirmDelete;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JPanel pDesc;
    private javax.swing.JPanel pPrincipal;
    // End of variables declaration//GEN-END:variables
}
